# --- analyze.py -----------------------------------------------------
MIN_CAT_FREQ = 3  # occorrenze minime del termine nella categoria
MIN_DOC_FREQ = 3  # documenti distinti in cui deve comparire
MIN_PURITY = 0.75  # quota delle occorrenze totali per categoria
MAX_TOKENS = 4

# --- seed.py --------------------------------------------------------
MAX_TERMS = 150  # n max di termini per categoria nel seed_dict.json

# Dict: Infobox key -> categoria QI
BOX_KEY_TO_CATEGORY = {
    # temporal
    "birth_date": "temporal",
    "death_date": "temporal",
    "years_active": "temporal",
    "yearsactive": "temporal",
    "years": "temporal",
    "term_start": "temporal",
    "term_end": "temporal",
    "debutdate": "temporal",
    "finaldate": "temporal",
    "date": "temporal",
    # location
    "birth_place": "location",
    "death_place": "location",
    "residence": "location",
    "origin": "location",
    "country": "location",
    "state": "location",
    "nationality": "nationality",
    # education
    "alma_mater": "education",
    "education": "education",
    "college": "education",
    "highschool": "education",
    "university": "education",
    # occupation
    "occupation": "occupation",
    "profession": "occupation",
    "position": "occupation",
    "role": "occupation",
    "field": "occupation",
    "rank": "occupation",
    # political_role
    "party": "political_role",
    "office": "political_role",
    "title": "political_role",
    "order": "political_role",
    "constituency": "political_role",
    # religion
    "religion": "religion",
    "denomination": "religion",
}

# l'unica componente supervisionata della pipeline
BASE_SEEDS = {
    "education": [
        "Harvard University",
        "Yale University",
        "University of Oxford",
        "University of Cambridge",
        "Stanford University",
        "MIT",
        "Princeton University",
        "Columbia University",
        "University of Michigan",
        "Boston College",
        "theological seminary",
        "military academy",
        "high school",
        "PhD",
        "doctorate",
        "bachelor",
        "master",
        "postdoctoral",
    ],
    "location": [
        "New York",
        "London",
        "Paris",
        "Berlin",
        "Rome",
        "Tokyo",
        "Moscow",
        "Sydney",
        "Toronto",
        "Chicago",
        "Boston",
        "Los Angeles",
        "Glasgow",
        "Munich",
        "Ljubljana",
        "California",
        "Texas",
        "Ohio",
        "Pennsylvania",
        "Ontario",
        "Bavaria",
        "England",
        "France",
        "Germany",
        "Italy",
        "Japan",
        "city",
        "town",
        "village",
        "province",
        "county",
        "region",
        "capital",
        "neighborhood",
    ],
    "nationality": [
        "American",
        "British",
        "French",
        "German",
        "Italian",
        "Canadian",
        "Australian",
        "Indian",
        "Chinese",
        "Spanish",
        "Russian",
        "Dutch",
        "Japanese",
        "Brazilian",
        "Irish",
        "Swedish",
        "Norwegian",
        "Polish",
        "Greek",
        "Turkish",
        "Cuban",
        "Mexican",
        "Argentine",
        "South African",
        "Israeli",
        "Iranian",
        "Egyptian",
        "Korean",
        "Pakistani",
        "Nigerian",
        "Scottish",
        "Welsh",
        "Belgian",
        "Swiss",
        "Austrian",
        "Danish",
        "Finnish",
        "Czech",
        "Hungarian",
        "Romanian",
    ],
    "occupation": [
        "doctor",
        "surgeon",
        "physician",
        "nurse",
        "engineer",
        "architect",
        "designer",
        "inventor",
        "lawyer",
        "judge",
        "attorney",
        "professor",
        "scientist",
        "researcher",
        "artist",
        "painter",
        "musician",
        "composer",
        "writer",
        "journalist",
        "author",
        "poet",
        "athlete",
        "coach",
        "trainer",
        "entrepreneur",
        "executive",
        "director",
        "pilot",
        "soldier",
        "astronaut",
        "chef",
        "actor",
        "teacher",
        "farmer",
        "businessman",
    ],
    "political_role": [
        "president",
        "vice president",
        "senator",
        "congressman",
        "prime minister",
        "chancellor",
        "secretary of state",
        "governor",
        "mayor",
        "minister",
        "ambassador",
        "deputy",
        "representative",
        "envoy",
        "member of parliament",
        "cabinet minister",
        "Republican",
        "Democrat",
        "Conservative",
        "Labour",
        "Liberal Democrat",
        "Communist Party",
    ],
    "religion": [
        "Jewish",
        "Catholic",
        "Roman Catholic",
        "Muslim",
        "Christian",
        "Protestant",
        "Buddhist",
        "Hindu",
        "Eastern Orthodox",
        "Evangelical",
        "Baptist",
        "Lutheran",
        "Presbyterian",
        "Anglican",
        "Methodist",
        "Sikh",
        "atheist",
        "Islam",
        "Judaism",
        "Buddhism",
    ],
    "temporal": [
        "january",
        "february",
        "march",
        "april",
        "may",
        "june",
        "july",
        "august",
        "september",
        "october",
        "november",
        "december",
        "spring",
        "summer",
        "autumn",
        "winter",
        "years old",
        "aged",
        "decade",
        "century",
        "year",
        "month",
        "week",
        "19th century",
        "20th century",
        "21st century",
        "early 20th century",
        "1920s",
        "1960s",
        "1980s",
        "the late 1990s",
        "mid-1970s",
    ],
}
